apiVersion: v1
kind: Service
metadata:
  name: bl-mem-store
  namespace: index
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    name: bl-mem-store
  selector:
    app: redis
    role: slave
    tier: backend
---

