#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: redis-master
#  labels:
#    name: redis-master
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        name: redis-master
#    spec:
#      containers:
#      - name: master
#        image: redis
#        ports:
#        - containerPort: 6379
#
#---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
  selector:
    app: redis
    role: master
    tier: backend